"""create a state visited model

Revision ID: 4277e6e54585
Revises: c372340cb301
Create Date: 2025-01-06 14:42:33.845735

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4277e6e54585'
down_revision = 'c372340cb301'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('visited_cities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('state_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['state_id'], ['states.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('visited_cities')
    # ### end Alembic commands ###
