"""update cities model

Revision ID: b7fa3171d562
Revises: 4d6cac3df783
Create Date: 2024-12-26 22:30:35.049187

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7fa3171d562'
down_revision = '4d6cac3df783'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('image', sa.String(), nullable=False),
    sa.Column('country_capital', sa.Boolean(), nullable=False),
    sa.Column('state_capital', sa.Boolean(), nullable=False),
    sa.Column('states_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['states_id'], ['states.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cities')
    # ### end Alembic commands ###
