"""create profile picture model

Revision ID: dbde74ba6392
Revises: 6ac0dc7e155f
Create Date: 2025-01-07 17:23:48.166869

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dbde74ba6392'
down_revision = '6ac0dc7e155f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profile_pictures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('picture_route', sa.String(), server_default='https://static.vecteezy.com/system/resources/thumbnails/008/442/086/small/illustration-of-human-icon-user-symbol-icon-modern-design-on-blank-background-free-vector.jpg', nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('profile_pictures')
    # ### end Alembic commands ###
