"""update users model

Revision ID: dcbfeee16706
Revises: 
Create Date: 2025-01-01 20:28:41.227653

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dcbfeee16706'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('continents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('image', sa.String(), nullable=False),
    sa.Column('intro', sa.String(), server_default='', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('countries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('image', sa.String(), nullable=False),
    sa.Column('safety_level', sa.String(), nullable=False),
    sa.Column('intro', sa.String(), server_default='', nullable=False),
    sa.Column('flag', sa.String(), server_default='', nullable=False),
    sa.Column('passport_stamp', sa.String(), server_default='', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('industries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('industry', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('industry')
    )
    op.create_table('sign_up_containers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('background_image', sa.String(), nullable=True),
    sa.Column('tex_background_colour', sa.String(), server_default='', nullable=False),
    sa.Column('title', sa.String(), server_default='', nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('container_polaroids',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('polaroid_picture', sa.String(), nullable=False),
    sa.Column('polaroid_text', sa.String(), nullable=False),
    sa.Column('container_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['container_id'], ['sign_up_containers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('countries_continents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('country_id', sa.Integer(), nullable=True),
    sa.Column('continent_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['continent_id'], ['continents.id'], ),
    sa.ForeignKeyConstraint(['country_id'], ['countries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('states',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('image', sa.String(), nullable=False),
    sa.Column('intro', sa.String(), server_default='', nullable=False),
    sa.Column('country_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['country_id'], ['countries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('image', sa.String(), nullable=False),
    sa.Column('intro', sa.String(), server_default='', nullable=False),
    sa.Column('country_capital', sa.Boolean(), nullable=False),
    sa.Column('state_capital', sa.Boolean(), nullable=False),
    sa.Column('states_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['states_id'], ['states.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('boroughs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('image', sa.String(), nullable=False),
    sa.Column('intro', sa.String(), server_default='', nullable=False),
    sa.Column('cities_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cities_id'], ['cities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('neighbourhoods',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('image', sa.String(), nullable=False),
    sa.Column('intro', sa.String(), server_default='', nullable=False),
    sa.Column('boroughs_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['boroughs_id'], ['boroughs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('_password_hash', sa.String(), nullable=False),
    sa.Column('account_type', sa.String(), nullable=False),
    sa.Column('intro', sa.String(), nullable=True),
    sa.Column('country_id', sa.Integer(), nullable=True),
    sa.Column('state_id', sa.Integer(), nullable=True),
    sa.Column('cities_id', sa.Integer(), nullable=True),
    sa.Column('boroughs_id', sa.Integer(), nullable=True),
    sa.Column('neighbourhoods_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['boroughs_id'], ['boroughs.id'], ),
    sa.ForeignKeyConstraint(['cities_id'], ['cities.id'], ),
    sa.ForeignKeyConstraint(['country_id'], ['countries.id'], ),
    sa.ForeignKeyConstraint(['neighbourhoods_id'], ['neighbourhoods.id'], ),
    sa.ForeignKeyConstraint(['state_id'], ['states.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('businesses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_name', sa.String(), nullable=False),
    sa.Column('opening_time', sa.Time(), nullable=False),
    sa.Column('closing_time', sa.Time(), nullable=False),
    sa.Column('phone_number', sa.String(), nullable=False),
    sa.Column('building_number', sa.String(), nullable=False),
    sa.Column('street_name', sa.String(), server_default='', nullable=False),
    sa.Column('post_code', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('travelers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('dob', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('business_industries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=True),
    sa.Column('industry_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.ForeignKeyConstraint(['industry_id'], ['industries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('business_industries')
    op.drop_table('travelers')
    op.drop_table('businesses')
    op.drop_table('users')
    op.drop_table('neighbourhoods')
    op.drop_table('boroughs')
    op.drop_table('cities')
    op.drop_table('states')
    op.drop_table('countries_continents')
    op.drop_table('container_polaroids')
    op.drop_table('sign_up_containers')
    op.drop_table('industries')
    op.drop_table('countries')
    op.drop_table('continents')
    # ### end Alembic commands ###
