"""add an initial_signin variable to all travelers model

Revision ID: f3db79ca0b90
Revises: f5b4095f1304
Create Date: 2025-01-03 21:14:39.637397

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3db79ca0b90'
down_revision = 'f5b4095f1304'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('travelers', schema=None) as batch_op:
        batch_op.drop_column('initial_signin')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('initial_signin', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('initial_signin')

    with op.batch_alter_table('travelers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('initial_signin', sa.BOOLEAN(), nullable=True))

    # ### end Alembic commands ###
