"""add an initial_signin variable to traveler model

Revision ID: f5b4095f1304
Revises: dcbfeee16706
Create Date: 2025-01-03 21:05:42.535443

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f5b4095f1304'
down_revision = 'dcbfeee16706'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('travelers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('initial_signin', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('travelers', schema=None) as batch_op:
        batch_op.drop_column('initial_signin')

    # ### end Alembic commands ###
